environment:
  nodejs_version: "0.10"

install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - git config user.email "tm-build@securityinnovation.com"
  - git config user.name "tm-build"

  - ssh git@github.com

  - npm install > nul
  - npm install -g coffee-script > nul

  - coffee "src\send-message.coffee" "Starting TM CI Deploy"
  - git clone
  git@github.com:tm-build/tm-qa-azure.git
  git@github.com:tm-build/tm-qa-azure.git
  - git remote -v
  - ls tm-qa-azure
  - coffee "src\send-message.coffee" "Clone completed"

  #- curl --data "[tm-ci-workflow] about to trigger azure deployment" "https://securityinnovation.slack.com/services/hooks/slackbot?token=%SLACK_TOKEN%&channel=tm-deploy"
  #- node_modules/.bin/coffee test.coffee
  #- cd tm-qa-azure

  - coffee "src\send-message.coffee" "About to trigger azure deployment"
  - call git commit --allow-empty -m "empty commit from Appveyor to trigger azure deployment"
  - git push origin master

  #- cd ..
  #- echo "...done"

build: off
